"""
Aperiodic Parameter Extraction for Empty Room (Noise) Data.

This script fits the SpecParam (FOOOF) model to empty room PSDs to characterize
the background noise of the MEG system. It serves as a critical control to 
ensure that subject-level aperiodic results are not driven by sensor noise.

Processing Steps:
1. Loads the empty room PSD data generated by 'psd_emptyroom.py'.
2. Interpolates the 23.4 Hz noise (Golan's noise).
3. Configures a SpectralGroupModel with parameters identical to the 
   resting-state analysis to ensure comparability.
4. Fits the model to the defined frequency range (2-40 Hz).
5. Exports a .tsv file containing the aperiodic parameters (offset, 
   exponent) for each sensor in the empty room recordings.

Author: Maité Crespo García
Affiliation: MRC Cognition and Brain Sciences Unit, Cambridge, UK
Date: 22-Oct-2025 (last modified)
"""

# Imports
import argparse
from specparam.utils.spectral import interpolate_spectra
import json
import logging
logger = logging.getLogger(__name__)
import mne
import numpy as np
import os
import pandas as pd
from specparam import SpectralModel, SpectralGroupModel
import time

# =============================================================================
# --- Project-specific Settings ---
# =============================================================================
maindir = '' # path where the BIDS project folder is stored, e.g. '/home/CamCAN/data/'
bids_project_folder = '' # Name of the BIDS project folder, e.g. 'BIDS_long_P2_rest_arm1'

# --- Pipeline-specific variables ---
pipver = '' # any string to identify the version of the pipeline, e.g. 'v01'.
task = 'noise'
phases = ['p2', 'p5']
arms = [1, 2]
lfreq = 0.1 # Hz, high-pass filter cutoff frequency. 
hfreq = 145.0 # Hz, low-pass filter cutoff frequency. 
fsample = 300.0 # Hz, resampling frequency.
frange = f"{round(lfreq, 1)}-{int(hfreq)}Hz"
megtypes = ['mag', 'grad'] # sensor types to process. Options: 'mag', 'grad', 'eeg'

trans = False # Whether to use head transformation or not
zmm = 44 # destination z coordinate head position in mm

# Processed data to use for extraction of aperiodic parameters
proc = 'filt'  # 

overwrite = True # whether to overwrite existing files

cropdata = 50

# --- Package used for aperiodic fitting ---
package = 'specparam' #'fooof' # irasa

fitting_param = 'finley' #'schmidt' #'oursv2' 
jsonfile = os.path.join(f'aperiodic_fitting_params_{fitting_param}.json')

if os.path.exists(jsonfile):
    with open(jsonfile) as json_file:
        json_dict = json.load(json_file)
    
    epoch_duration = json_dict['epoch_duration']
    powmethod = json_dict['powmethod']
    fres = json_dict['fres']
    freq_range = json_dict['freq_range']
    peak_width_limits = json_dict['peak_width_limits']
    min_peak_height = json_dict['min_peak_height']
    peak_threshold = json_dict['peak_threshold']
    max_n_peaks = json_dict['max_n_peaks']
    frangestr = f'{freq_range[0]}-{freq_range[1]}Hz'
else:

    if fitting_param == 'oursv1':
        # ---- Variables from PSD computation ----
        epoch_duration = 10 # seconds
        powmethod = 'MT' # 'MT' for multitaper, 'W' for welch #
        
        fres = 0.1 # frequency resolution in Hz

        # ---- Variables for the aperiodic fitting ----
        # Define the frequency range to fit
        freq_range = [3, 35] # following suggestion in documentation #0.5-140 Hz in the paper, but we use 1-48 Hz to avoid 50 Hz noise
        frangestr = f'{freq_range[0]}-{freq_range[1]}Hz'
        peak_width_limits=[1, 6]
        min_peak_height=0.05
        peak_threshold=1.5
        max_n_peaks=6
    else:
        raise ValueError(f'Fitting parameter set "{fitting_param}" not recognized.') 


    fitting_param_dict = {
        'epoch_duration': epoch_duration,
        'powmethod': powmethod,
        'fres': fres,
        'freq_range': freq_range,
        'peak_width_limits': peak_width_limits,
        'min_peak_height': min_peak_height,
        'peak_threshold': peak_threshold,
        'max_n_peaks': max_n_peaks
    }

    json.dump(fitting_param_dict, open(f'aperiodic_fitting_params_{fitting_param}.json', 'w'), indent=4)

psddesc = f'dur{cropdata}sepo{epoch_duration}s{powmethod}'

# --- Directories and files ---

if trans:
    psd_deriv_folder = f'mne-bids-pipeline_{pipver}_filt{frange}_fs{int(fsample)}Hz_trans_z{zmm}mm'
else:
    psd_deriv_folder = f'mne-bids-pipeline_erm_filt{frange}_fs{int(fsample)}Hz'

if False:
    goodepochs_deriv_folder = 'mne-bids-pipeline_stier' # for bad epochs only (for 10s epochs)
else:
    goodepochs_deriv_folder = psd_deriv_folder

if trans:
    save_deriv_folder = f'aperiodic_filt{frange}_fs{int(fsample)}Hz_trans_z{zmm}mm'
else:
    save_deriv_folder = f'aperiodic_filt{frange}_fs{int(fsample)}Hz'

# ---- Logging ----
# Directory where the log file will be saved
taskref = 'rest'
phaseref = 'p5' 
armref = 1

save_deriv_root = os.path.join(maindir, bids_project_folder,
                        'derivatives', save_deriv_folder)
if not os.path.exists(save_deriv_root): os.makedirs(save_deriv_root)

logdir = os.path.join(save_deriv_root, 'logfiles')
if not os.path.exists(logdir): os.makedirs(logdir)

# Set up log file
logfile = os.path.join(logdir, f'aperiodic_long_emptyroom_{package}_{proc}_{frangestr}.log')
logging.basicConfig(filename=logfile, encoding='utf-8', level=logging.DEBUG)

# ---- File with subjects and arms ----
subjlistfile = os.path.join(maindir,f'meglong_{taskref}_subjects.tsv')

# Main code
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--subject', type=str, default=None, dest='subject', action='store')
    parser.add_argument('--phase', type=str, default=None, dest='phase', action='store')
    args = parser.parse_args()
    print(args)
    print(args.subject)
    print(args.phase)

    # Read file with subjects and arms
    subjectsdf = pd.read_csv(subjlistfile, sep='\t').set_index('subject')

    if args.subject is not None:
        subjects = [args.subject]
    else:
        subjects = subjectsdf.index.tolist()
        subjects = subjects[subjects.index('CC210088'):]

    if args.phase is not None:
        phases_to_process = [args.phase]
    else:
        phases_to_process = phases

    # loop over subjects
    for id in subjects:
        armx = subjectsdf.loc[id,'arm']
        
        for phase in phases_to_process:
            t0 = time.time()

            # ---- Define the output directory ----
            bids_project_folder = f'BIDS_long_{phase}_{taskref}_arm{armx}'
            save_derivdir = os.path.join(maindir, bids_project_folder,
                    'derivatives', save_deriv_folder)
            save_megdir = os.path.join(save_derivdir, 'sub-'+id, 'meg')
            if not os.path.exists(save_megdir):
                os.makedirs(save_megdir)

            # --- Define the psd directory and file ---
            psd_derivdir = os.path.join(maindir, bids_project_folder,
                    'derivatives', psd_deriv_folder)
            psd_megdir = os.path.join(psd_derivdir, 'sub-'+id, 'meg')

            psdfilename = f'sub-{id}_task-{task}_proc-{proc}_desc-{psddesc}_psd.hdf5'
            psdfile = os.path.join(psd_megdir, psdfilename)

            # --- Check if the psd file exists ---
            if not os.path.isfile(psdfile):
                msg = f'Subject {id} in phase {phase}: psd file not found, skipping.'
                print(msg)
                logger.warning(msg)
                continue
            
            # Loop over MEG sensor types
            for megtype in megtypes:

                    # --- Define the output file for aperiodic parameters ---
                    savefilename = f'sub-{id}_task-{task}_proc-{proc}_desc-{psddesc}{megtype}{fitting_param}_{package}.tsv'
                    savefile = os.path.join(save_megdir, savefilename)

                    # --- Check if the output file already exists ---
                    if os.path.isfile(savefile) and not overwrite:
                        msg = f'Subject {id} in phase {phase}, MEG type {megtype}: aperiodic parameters already computed, skipping.'
                        print(msg)
                        logger.info(msg)
                        continue
                    
                    # --- Read the power spectrum data ---
                    psd = mne.time_frequency.read_spectrum(psdfile)

                    # --- Get the psds for each epoch and channel ---
                    spectra, freqs = psd.pick(megtype).get_data(return_freqs=True)
                    
                    # --- Save the channels names ---
                    ch_names = psd.ch_names
                    del psd # free memory

                    # --- Average PSD across epochs ---
                    spectra = np.average(spectra, axis=0)

                    # ---- Interpolate 23.4 Hz (Golan's) noise ----
                    if package == 'specparam':
                        freqs, spectra = interpolate_spectra(freqs, spectra, [21.9, 23.9]) # channels x frequencies

                    if fres > 0.1 and epoch_duration == 10:                
                        spectra = mne.filter.resample(spectra, down=int(fres/0.1), pad='line', npad='auto', axis=1, method='polyphase')
                        freqs = np.linspace(freqs[0], freqs[-1], num=int((freqs[-1]-freqs[0])/fres)+1)
                        freqs = freqs[:len(spectra[0,:])]  # Adjust the frequencies to match the new data shape

                    if package == 'specparam':
                        # Initialize a SpectralGroupModel
                        fg = SpectralGroupModel(peak_width_limits=peak_width_limits, min_peak_height=min_peak_height,
                        peak_threshold=peak_threshold, max_n_peaks=max_n_peaks, 
                        aperiodic_mode = 'fixed', verbose=False)

                    # --- Fit the power spectrum model across all channels ---                    
                    fg.fit(freqs, spectra, freq_range)

                    # --- Save the group results (group means all the channels) ---
                    # Note: this saves the offset, exponent, and goodness of fit (R2, RMSE)
                    # for each channel.
                    df = fg.to_df(peak_org=max_n_peaks)

                    df['channel_name'] = ch_names  
                    
                    # Save the results to a TSV file
                    df.to_csv(savefile, sep='\t', index_label='channel')
                    
                    t1 = time.time()   
                    deltat = t1 - t0
                    msg = f'Subject {id} s aperiodic parameters computed in {deltat:.2f} seconds.'
                    print(msg)
                    logger.info(msg)
            

if __name__ == "__main__":
    main()