"""
Aggregate ECG SpecParam Results and Classify Cardiac Frequency Bands.

This script compiles individual ECG spectral parameters (generated by 
'specparam_ecg.py') into a single master dataset. It classifies any 
periodic peaks found in the ECG signal into standard frequency bands.

Processing Steps:
1. Iterates through all subjects and longitudinal phases.
2. Loads the individual ECG SpecParam .tsv files.
3. Maps detected cardiac peaks to frequency bands (Theta, Alpha, Beta, Gamma).
4. Selects the peak with the highest power if multiple peaks exist in a band.
5. Merges all subject data into a unified 'group_stats_ecg' master table.

Author: Maité Crespo García
Affiliation: MRC Cognition and Brain Sciences Unit, Cambridge, UK
Date: 08-Jan-2026 (last modified)
"""

# Imports
import json
import numpy as np
import os
import pandas as pd
import time
import logging
logger = logging.getLogger(__name__)

# =============================================================================
# --- Project-specific Settings ---
# =============================================================================
maindir = '' # path where the BIDS project folder is stored, e.g. '/home/CamCAN/data/'
bids_project_folder = '' # Name of the BIDS project folder, e.g. 'BIDS_long_P2_rest_arm1'

# --- Pipeline-specific variables ---
pipver = '' # any string to identify the version of the pipeline, e.g. 'v01'.
task = 'rest'
phases = ['p2', 'p5']
arms = [1, 2]

overwrite = False

dointerpolation = True # whether to do interpolation of 23.4 Hz noise
sinterp = '' if dointerpolation else '_nointerp'

# Processed data to use for extraction of aperiodic parameters
channelselection = 'ECG' # 'allbutecg04' #'eog08' # 
proc = 'sss' + channelselection #'sss' #'clean'
likemeg = True
slikemeg = 'likemeg' if likemeg else ''

# whether to use epochs or raw data
cropdata = 532 

# Define the frequency range to fit
##### Frequency Range used for the Aperiodic Fit ###
#freq_range = [3, 35] #0.5-140 Hz in the paper, but we use 1-30 Hz to avoid 50 Hz noise
#frangestr = f'{freq_range[0]}-{freq_range[1]}Hz'
method = 'specparam' #'fooof' # irasa
aperiodic_mode = 'fixed' # 'knee' or 'fixed', only relevant for fooof method

lfreq = 0.1 #Hz
hfreq = 145.0 #Hz
fsample = 300.0 #Hz
frange = f"{round(lfreq, 1)}-{int(hfreq)}Hz"

# Use non trans data for ECG
trans = False # Whether to use head transformation or not
zmm = 44 # destination z coordinate head position in mm

# --- Package used for aperiodic fitting ---
package = 'specparam' #'fooof' # irasa

fitting_param = 'finley' #'oursv2' # 'oursv1' #

jsonfile = os.path.join(f'aperiodic_fitting_params_{fitting_param}.json')
if os.path.exists(jsonfile):
    with open(jsonfile) as json_file:
        json_dict = json.load(json_file)
    
    epoch_duration = json_dict['epoch_duration']
    powmethod = json_dict['powmethod']
    fres = json_dict['fres']
else:
    raise FileNotFoundError(f'Fitting parameters file {jsonfile} not found.')

psddesc = f'dur{cropdata}sepo{epoch_duration}s{powmethod}'
sfres = '' if fres == 0.1 else f'fres{fres}Hz'

# --- Directories and files ---
if trans:
    load_deriv_folder = f'aperiodic_filt{frange}_fs{int(fsample)}Hz_trans_z{zmm}mm'
else:
    load_deriv_folder = f'aperiodic_filt{frange}_fs{int(fsample)}Hz'

# directory where the psd files were stored
taskref = 'rest'
phaseref = 'p5'
armref = 1
deriv_root = os.path.join(maindir, bids_project_folder,
                          'derivatives', load_deriv_folder)

logdir = os.path.join(deriv_root, 'logfiles')
if not os.path.exists(logdir):
    os.makedirs(logdir)
# Set up logging
logfile = os.path.join(logdir, f'aperiodic_ecg_long_sp_{proc}_{fitting_param}{sinterp}_createtsv.log')
logging.basicConfig(filename=logfile, encoding='utf-8', level=logging.DEBUG)

statsdir = os.path.join(deriv_root, 'stats')
if not os.path.exists(statsdir):
    os.makedirs(statsdir)

# ---- File with subjects and arms ----
subjlistfile = os.path.join(maindir, f'meglong_{task}_subjects.tsv')

# This file contains all the subjects in the longitudinal study, with the age at each phase
agefilename = os.path.join(maindir,f'meglong_{task}_age.tsv')

bandsdiv = '2betas' # whether to divide beta into 2 or 3 sub-bands

if bandsdiv == '3betas':
    # --- Variables of interest ---
    varsoi = ['exponent', 
                'theta_peak_freq', 'theta_band_power', 
                'alpha_peak_freq', 'alpha_band_power',
                'low_alpha_peak_freq', 'low_alpha_band_power',
                'high_alpha_peak_freq', 'high_alpha_band_power',
                'beta_peak_freq', 'beta_band_power', 
                'low_beta_peak_freq', 'low_beta_band_power',
                'middle_beta_peak_freq', 'middle_beta_band_power',
                'high_beta_peak_freq', 'high_beta_band_power',
                'gamma_peak_freq', 'gamma_band_power',
                'r_squared',]

    bandsdict = {
                'theta':(4,8),
                'alpha':(8,13),
                'beta':(15,30),
                'low_alpha':(8,10),
                'high_alpha':(10,13),
                'low_beta':(13,15),
                'middle_beta':(15,20),
                'high_beta':(20,30),
                'gamma':(30,48),
                }
    
elif bandsdiv == '2betas':
    varsoi = ['exponent', 
                'theta_peak_freq', 'theta_band_power', 
                'alpha_peak_freq', 'alpha_band_power',
                'beta_peak_freq', 'beta_band_power',
                'low_alpha_peak_freq', 'low_alpha_band_power',
                'high_alpha_peak_freq', 'high_alpha_band_power',
                'low_beta_peak_freq', 'low_beta_band_power',
                'high_beta_peak_freq', 'high_beta_band_power',
                'gamma_peak_freq', 'gamma_band_power',
                'r_squared',]

    bandsdict = {
                'theta':(4,8),
                'alpha':(8,12),
                'beta':(12,30),
                'low_alpha':(8,10),
                'high_alpha':(10,12),
                'low_beta':(12,20),
                'high_beta':(20,30),
                'gamma':(30,48),
                }
    
    if aperiodic_mode == 'fixed':
        varsoi = ['r_squared']

# --- Functions ---
# Main code
def main():
    # Read file with subjects and arms
    subjectsdf = pd.read_csv(subjlistfile, sep='\t').set_index('subject')
    subjects = subjectsdf.index.tolist()

    age = pd.read_csv(agefilename, sep='\t').set_index('ccid')
    age.rename(columns={'p2_meg_age':'p2_age', 'p5_meg_age':'p5_age'}, inplace=True)
    
    
    columns = []
    for var in varsoi:
        bandname = get_bandname(var)
        if bandname:
            fbandrange = bandsdict[bandname] #0.5-140 Hz in the paper, but we use 1-30 Hz to avoid 50 Hz noise
            fband = f'{fbandrange[0]}-{fbandrange[1]} Hz'
        
        # Create a datafile for each megtype and variable of interest,
        # containing all the subjects, phases, age, and channels
        createdf = True
        datafile = os.path.join(
            statsdir, f'aperiodic_stier_{proc}{slikemeg}_{fitting_param}{aperiodic_mode if aperiodic_mode=='fixed' else ''}_{var}_{bandsdiv}{sinterp}.tsv'
            )
        
        # --- Create the datafile ---
        # with values of the variable of interest, per participant, phase, alongside the
        # age at phase 2, age lag between p5 and p2, in the long format. To be used as an
        # input for statistical analyses (LME)
        if not os.path.isfile(datafile) or overwrite:
            # Code creating the datafile here
            # Create a the dataframe with the variable of interest, and save it
            # in the long format, for statistics
            for phase in phases:                   
                # loop over subjects within this age group
                for id in subjects: 
                    armx = subjectsdf.loc[id,'arm']

                    # ---- Define the load directory ----
                    bids_project_folder = f'BIDS_long_{phase}_{task}_arm{armx}'
                    load_derivdir = os.path.join(maindir, bids_project_folder,
                            'derivatives', load_deriv_folder)
                    save_megdir = os.path.join(load_derivdir, 'sub-'+id, 'meg')
                    if not os.path.exists(save_megdir):
                        os.makedirs(save_megdir)

                    # --- Define the load file for aperiodic parameters ---
                    loadfilename = f'sub-{id}_task-{task}_proc-{proc}{slikemeg}_desc-{psddesc}{fitting_param}{aperiodic_mode if aperiodic_mode=='fixed' else ''}_{package}{sinterp}.tsv'
                    loadfile = os.path.join(save_megdir, loadfilename)

                    # Check if the files already exist
                    if not os.path.isfile(loadfile): 
                        if os.path.isfile(os.path.join(save_megdir, 'error.txt')):
                            msg = (
                                f'Error file found for subject {id} phase {phase} ECG.'
                                ' Skipping this subject.'
                            )
                            print(msg)
                            logger.warning(msg)
                            continue
                        else:
                            msg = (
                                f'Please, run aperiodic sp script first. The '\
                                'the file below does not exist:'
                                f'\\n{loadfile}'
                            )
                            #print(msg)
                            #logger.error(msg)
                            raise FileNotFoundError(msg)
                    
                    else:
                        print(f'Processing variable {var} for subject {id} phase {phase} ECG')
                        # Load the tsv file with the aperiodic parameters, for each subject
                        df = pd.read_csv(loadfile, sep='\t').set_index('channel')
                        #print(df.columns.tolist())

                        # create the list with column names only once
                        if len(columns) == 0:
                            columns = ['subject', 'task', 'phase', 'Age0', 'deltaAge']
                            colchans = len(columns)
                            columns.extend(['ECG'])

                        if createdf:
                            newdf = pd.DataFrame(columns=columns)
                            createdf = False

                        newidx = newdf.index.max() + 1 if not newdf.empty else 0
                                                                                
                        newdf.loc[newidx, 'subject'] = id
                        newdf.loc[newidx, 'task'] = task
                        newdf.loc[newidx, 'phase'] = phase
                        newdf.loc[newidx, 'Age0'] = age.loc[id, 'p2_age']
                        if phase == 'p2':                        
                            newdf.loc[newidx, 'deltaAge'] = 0
                        elif phase == 'p5':
                            newdf.loc[newidx, 'deltaAge'] = age.loc[id, 'p5_age'] - age.loc[id, 'p2_age']

                        # Check if the variable of interest is in the dataframe    
                        if bandname:
                            print(var)
                            newdf.loc[newidx, 'ECG'] = add_var_row(df, var, bandname, bandsdict[bandname])

                        elif var in df.columns: 
                            # Get the data for this variable
                            newdf.loc[newidx, 'ECG'] = df[var].values

                        else:
                            print(f'{var} is was not extracted from the table')


            # Save the data to a tsv file
            newdf.to_csv(datafile, sep='\t', index=True, index_label='row')
            msg = f'File {datafile} created.'
            print(msg)
            logger.info(msg)

        else:
            msg = f'File {datafile} was already created.'
            print(msg)
            logger.info(msg)

            

def get_bandname(var):
    bandname = []
    for name in ['theta', 'low_alpha', 'high_alpha', 'low_beta', 'middle_beta', 'high_beta']:
        if name in var:
            bandname = name
            return bandname
            
    if not bandname:
        for name in ['alpha', 'beta', 'gamma']:
            if name in var:
                bandname = name
                return bandname
    
    return bandname

def add_var_row(df, var, bandname, frange):
    # add a column with the variable name
    df[var] = ''

    prefix = []     
    if 'peak_freq' in var:
        prefix = 'cf'
    elif 'band_power' in var:
        prefix = 'pw'
    elif 'band_width' in var:
        prefix = 'bw'

    fcols = []
    for col in df.columns:
        if 'cf' in col:
            fcols.append(col)
    #print(fcols)

    pcols = []
    for col in df.columns:
        if 'pw' in col:
            pcols.append(col)
    #print(pcols)

    if bandname:
        for i in df.index: # for each channel
            idx = np.where((df.loc[i, fcols] >= frange[0]) & (df.loc[i, fcols] < frange[1]))[0].tolist()
            #print(idx)
            if len(idx) > 1:
                selcols = [pcols[j] for j in idx]
                #print(selcols)
                #print(df.loc[i, selcols])
                #print(df.loc[i, selcols].max())
                idxmax = np.where(df.loc[i, selcols] == df.loc[i, selcols].max())[0].tolist()
                idx = idx[idxmax[0]]
            elif len(idx) == 1:
                idx = idx[0]
            else:
                idx = None

            if idx is not None:
                df.loc[i, var] = df.loc[i, f'{prefix}_{str(idx)}']
        
    return df[var].values
                
if __name__ == "__main__":
    main()